### ISSUE TITLE
[Question] Can i found somewhere a list of ISO 3166 states ?

### ISSUE THREAD

**Issue by abenevaut** [lukes/ISO-3166-Countries-with-Regional-Codes#12]
Can i found somewhere a repository with a list of ISO 3166 states ?

Here is what i complete for now, for a [PHP Laravel library](https://github.com/CavaENCOREparlerdebits/laravel-addresses/blob/master/src/database/seeds/StatesSeeder.php), but that very very long to parse and add data from wikipedia.

https://fr.wikipedia.org/wiki/ISO_3166-2:CA
https://fr.wikipedia.org/wiki/ISO_3166-2:US
https://fr.wikipedia.org/wiki/ISO_3166-2:MX
https://fr.wikipedia.org/wiki/ISO_3166-2:FR

**Comment by 42antoine** [comment]
More precise i found https://github.com/niallkennedy/ISO-3166/blob/master/iso3166.php

Any one can propose me another list ?

**Comment by cocowalla** [comment]
It's avaiilable in CSV format [here](https://www.ip2location.com/free/iso3166-2)

**Comment by lukes** [comment]
@abenevaut I'll close this issue now.
