### ISSUE TITLE
Latest update is missing

### ISSUE THREAD

**Issue by dknaack** [lukes/ISO-3166-Countries-with-Regional-Codes#14]
Hi!

At first, thank you for this repo!

In your readme you say that you have updated the data to August 2016.
I cant find this update in this repo.

Please help.

Thanks!

**Comment by lukes** [comment]
Hi, a good question!

I ran the update scripts over the data in August 2016 - but as it happens were no changes to the data since 2015, and so it appears as if the repo hasn't been updated when it has.

**Comment by dknaack** [comment]
Ah interesting! Thanks!
