### ISSUE TITLE
Taiwan, Province of China rename to Taiwan

### ISSUE THREAD

**Issue by SickAssApp** [lukes/ISO-3166-Countries-with-Regional-Codes#22]
Hi, appreciate for the great work, but Taiwan does not belong to Province of China right now, since there's still an independent form of government in Taiwan and people from China cannot enter Taiwan without passport or any VISA.
This is a controversial issue for a long time, and it is not settled until now, so I'll be appreciate if you can change the name of this place to Taiwan, which is the name that most of the people live in this place think it should be.

Thank you.

**Comment by lukes** [comment]
Hi, 

Thank you for your comment. Yes, indeed I'm aware of the controversy. I make no actual decision on the names in the data myself, the data is a pure reflection of the IOS-3166 standard.

I'm aware of a long-running discussion over the name. 

From wikipedia:

>The ISO 3166 directory of names of countries and territories registers Taiwan (TW) separately from and in addition to the People's Republic of China (CN), but lists Taiwan as "Taiwan, Province of China" based on the name used by the UN under PRC pressure. In ISO 3166-2:CN, Taiwan is also coded CN-71 under China, thus making Taiwan part of China in ISO 3166-1 and ISO 3166-2 categories.
> https://en.wikipedia.org/wiki/Political_status_of_Taiwan

There's also a section on the ISO-3166 page https://en.wikipedia.org/wiki/ISO_3166-1#Naming_and_disputes that mentions the naming dispute. 

I hope you understand what this data is intended to be (a reflection of ISO-3166 standard) and what it isn't intended to be (a comment about the status of any nation in the data source).

**Comment by SickAssApp** [comment]
Hi,
I understand now.
Thank you for your reply and detail information on the reason, appreciate your work here.

**Comment by lukes** [comment]
You're welcome! Would you mind if I closed this issue now?

**Comment by SickAssApp** [comment]
No, not at all, close this issue please, thank you.

**Comment by babebbu** [comment]
a country that is valid to be a country is a country, no matter what, nor any pressure from PRC.
