### ISSUE TITLE
Missing Kosovo

### ISSUE THREAD

**Issue by volfco** [lukes/ISO-3166-Countries-with-Regional-Codes#29]
I noticed that Kosovo (XK) is missing.

**Comment by lukes** [comment]
From what I understand from https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements

> The code XK is being used by the European Commission,[24] the IMF, and SWIFT,[25] CLDR and other organizations as a temporary country code for Kosovo.[26]

And from the page linked from that footnote https://geonames.wordpress.com/2010/03/08/xk-country-code-for-kosovo/

> The European Commission and many other organisations (Deutsche Bundesbank, Switzerland) are using ‘XK‘ as a temporary country code for Kosovo till ISO officially assigns a code.

As this data-set represents the official codes, and not "user-defined" codes, it's correct to not include Kosovo in the data-set (yet - until it is assigned a code!).

Note, you can certainly feel free to fork this repository and add it yourself for your own purposes!
