### ISSUE TITLE
Netherlands Antilles not in the list

### ISSUE THREAD

**Issue by Dianaelena85** [lukes/ISO-3166-Countries-with-Regional-Codes#37]
Could you please add the Netherlands Antilles into the list?

**Comment by lukes** [comment]
@Dianaelena85 The two data sources the lists use don't list Netherlands Antilles:

- https://en.wikipedia.org/wiki/ISO_3166-1
- https://unstats.un.org/unsd/methodology/m49/overview

Without having any prior knowledge of Netherlands Antilles, Wikipedia suggests that it was dissolved in 2010 and no longer exists https://en.wikipedia.org/wiki/Netherlands_Antilles#Dissolution. Does that seem the case?

**Comment by lukes** [comment]
I close this issue, but reopen if there is anything else to consider.
