### ISSUE TITLE
some country name is strange

### ISSUE THREAD

**Issue by talebook** [lukes/ISO-3166-Countries-with-Regional-Codes#46]
Some country name is strange, looks like it's been chuncated.  I think the name should be more human readable.
For Example, `Korea (Democratic People's Republic of)` should be full name`Korea (Democratic People's Republic of Korea)` or [common name](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) `North Korea`.

```
$ cat all.json | jq ".[].name" | grep of
"Bolivia (Plurinational State of)"
"Congo, Democratic Republic of the"
"Iran (Islamic Republic of)"
"Isle of Man"
"Korea (Democratic People's Republic of)"
"Korea, Republic of"
"Micronesia (Federated States of)"
"Moldova, Republic of"
"Palestine, State of"
"Taiwan, Province of China"
"Tanzania, United Republic of"
"United Kingdom of Great Britain and Northern Ireland"
"United States of America"
"Venezuela (Bolivarian Republic of)"
```

**Comment by lukes** [comment]
@talebook Thanks for your issue! This dataset reflects ISO-3166 https://en.wikipedia.org/wiki/ISO_3166 you can see the names of the countries defined in ISO-3166-1 https://en.wikipedia.org/wiki/ISO_3166-1.
