### ISSUE TITLE
availability as a npm package

### ISSUE THREAD

**Issue by y-nk** [lukes/ISO-3166-Countries-with-Regional-Codes#59]
Hello,

I'd like to know if you were interested into a PR which would add a `package.json` file in order to publish to the node package manager registry.

This would allow people to use the json (and other formats, but mostly json) directly from their dependencies in any javascript project.

I'd be happy to help on that, let me know.

**Comment by y-nk** [comment]
👋

**Comment by lukes** [comment]
@y-nk I think that is a good initiative, but it's not something I want to maintain. This could be something that another person could do as a downstream if they wish 🙇

**Comment by y-nk** [comment]
@lukes i will setup a repo and automate the build with github actions if that's ok with you. would you consider adding informations in the upstream README to inform about package availability?

similarly, i wonder how to categorise version changes as you publish them, as you know in most package managers there's usually a semver produced. an easy way for downstream to know what kind of change is made would be to introduce conventional commits upstream (here) so downstreams would know what you consider major/minor/patch ; or it could be resolved case by case (but i don't know how often this repo updates). What would be your recommendations?
