### ISSUE TITLE
Missing Kosovo XK

### ISSUE THREAD

**Issue by filip-arkose** [lukes/ISO-3166-Countries-with-Regional-Codes#60]
Missing Kosovo country code which is XK

https://en.wikipedia.org/wiki/.xk#:~:text=xk%20is%20a%20temporary%2C%20unofficial,Council%20Resolution%201244%20in%201999.&text=XK%20falls%20under%20the%20ISO,QZ%20and%20XA%20to%20XZ.

**Comment by BStrauss3** [comment]
A search of ISO doesn't show XK in any of the catagories ISO maintains, just as an autonomous province: https://www.iso.org/obp/ui/#iso:code:3166:RS

Wikipedia is not a stable primary source. Especially in contentious issues.

Unfortunately whatever decision you make as a technologist (or as a numismatist, or as a historian FWIW) means you implicitly take sides. Often without meaning to and with no specific intention.

The simplest technological solution is to create an automated extract from a primary source and inform people how to make changes to allow for their personal preferences. It's what I've done in my passion projects.

-----Burton

**Comment by filip-arkose** [comment]
Thanks for the quick reply, totally understand. Thanks for this resource.

**Comment by BStrauss3** [comment]
Oh, i'm just another user like you, i've just been fighting the same battle on my passion project.... 

When NGC issues a (coin) sample using a 1923 Weimar Republic German coin, what code do I use? 

Technically DEU is the Federal Republic of Germany, the successor to occupied Germany and no relation to 1923 other than some of the same physical land.

Weinmar is the successor to the German Empire and the predecessor of Nazi Germany (Technically the German Reich (1933-1943) and then the Greater German Reich (1943-1945). None of which have ISO 3166 codes :-)

Which leads to occupied Germany, the DEU/DDR split (which have historical ISO3166 codes) and finally to today's Germany (DEU). 

Connecting 1923 to DEU them is bunk, it's Wikipedia level history. And then I told then we were numismatists not historians and deal with it :-).

-----Burton

**Comment by lukes** [comment]
Thank you for the discussion. I'll close this as the source is the ISO 3166 data.
