### ISSUE TITLE
Another source

### ISSUE THREAD

**Issue by gottlike** [lukes/ISO-3166-Countries-with-Regional-Codes#7]
Just FYI, heres another potential source: https://www.cia.gov/library/publications/the-world-factbook/appendix/appendix-d.html

I don't know how accurate and up-to-date it is, though.

**Comment by lukes** [comment]
Thanks, I appreciate the link. Doing a quick correlation between the linked data and ISO-3166, there's enough differences to make me consider not using it as a source.
